import { hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { getLocale, setRequestLocale } from "next-intl/server";
import { routing } from "@/i18n/routing";
import Providers from "@/components/providers";
import { Inter, Zain } from "next/font/google";
import React from "react";
import { cn } from "@/lib/utils";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--font-inter",
});

const zain = Zain({
  subsets: ["latin"],
  weight: ["300", "400", "700", "800"],
  display: "swap",
  variable: "--font-zain",
});

//Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// Generate all possible locale-based route parameters for Next.js to pre-render at build time
export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({ children }: { children: React.ReactNode }) {
  const locale = await getLocale();
  // Enable static rendering
  setRequestLocale(locale);
  if (!hasLocale(routing.locales, locale)) {
    return notFound();
  }

  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <body
        className={cn(
          "rtl:text-lg",
          locale === "en" ? inter.variable : zain.variable,
          locale === "en" ? inter.className : zain.className,
          locale === "ar" ? "text-2xl" : "text-base",
        )}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
